### PR TITLE
Test

### PR DESCRIPTION
**Pull request by pasthalal**
Only check the commit on jan 16.

### CODE REVIEW

**Comment by ashabed** [comment]
1) You named the feature 'application'. It's better to have something personal in the name, like debugacademy_application (or da_application). That way, if there ever is a module from drupal.org named 'application', they won't be a problem with us having both installed.

2) "Only check the commit on jan 16." - this type of pull request wouldn't be accepted on a well run development teams, so let's get the pull request created without extra commits.

In this case it isn't too difficult because you'll have to rename the feature anyways. Go to master, create a new branch, re-create the feature there, and commit it / submit a pull request for that branch. It is also possible to 'delete' commits, but we can avoid that for now.

**Comment by pasthalal** [comment]
Thank you for the feedback. Sorry for the extra commits. I'll rename the
feature and commit it.

**Comment by ashabed** [comment]
I left 1 comment that you should have received a notification about saying the module's name isn't changed, only the label got changed. The application feature will need to be re created to truly reset the name.

Second comment is that this pull request is adding a number of modules that I don't think are relevant to what the pull request should be for. For example 'field_tools' and 'updated_blog'. I'm guessing field_tools isn't used, and updated_blog should be on another branch in its own pull request..?

**Comment by ashabed** [comment]
Closing this pull request because it's outdated.

**Pull request closed without merging**
